service:
  name: serverless-ts-testing

custom:
  # Setup for local dynamodb
  dynamodb:
    stages:
      - dev

plugins:
  - serverless-webpack
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs8.10
  #stage: prod
  #profile: prod
  stage: dev
  profile: dev
  region: eu-central-1
  environment:
    CONTAINER_TABLE_NAME: ${self:service}-${self:provider.stage}-container


functions:

  addContainer:
    handler: lambda/api/container/ContainerController.addContainer
    events:
      - http:
          method: post
          path: container

  getContainer:
    handler: lambda/api/container/ContainerController.getContainer
    events:
      - http:
          method: get
          path: container


resources:
  Resources:

    # DynamoDB - container
    # Just some sample schema for containers
    containerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-container
        AttributeDefinitions:
          - AttributeName: lotId
            AttributeType: S
          - AttributeName: containerId
            AttributeType: S
        KeySchema:
          - AttributeName: containerId
            KeyType: HASH
          - AttributeName: lotId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
